### PR TITLE
Propose a fix for the issue #253 by not comparing IDatetime fields wh…

### PR DESCRIPTION
**Pull request by sneridagh**
…en patching and set the value always.

### CODE REVIEW

**Comment by sneridagh** [comment]
@tisto @buchi @lukasgraf It's the simplest and less intrusive solution that I could think of to solve this problem. Let me know what do you think.

**Comment by lukasgraf** [comment]
I haven't been involved with this part of the original implementation, so I'm afraid I can't really give any meaningful feedback without fully diving into it.

**Comment by buchi** [comment]
This will only work around the error you currently get when trying to create an event through the REST API. However you get an event with start/end dates without tzinfo which is inconsistent to events created through the web. Most likely this will lead to errors when viewing/editing the event with Plone's default views/forms. See discussion in #253

**Comment by sneridagh** [comment]
Closing in favor of: #394

**Pull request closed without merging**
