### PR TITLE
Handle remoteUrl field for Links

### PR DESCRIPTION
**Pull request by cekk**
This is related to https://github.com/plone/volto/pull/1899

I added a serializer and deserializer for TextLine field for Link objects and:
- if it's an internal link (starts with portal_url), deserialize it like "classic" Plone
- if it's an internal link, serialize it converting into a resolved url

### CODE REVIEW

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@tisto this one is required for a change already merged in Volto.

**Comment by sneridagh** [comment]
@cekk some of the tests fails for some reason, could you take a look?

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by cekk** [comment]
@sneridagh fixed some black issues..waiting for jenkins

**Comment by cekk** [comment]
Ok, it's all green except a random Robot test

**Review by tisto — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
