### PR TITLE
implement "sort" feature to rearrange all folder items

### LINKED ISSUE #812: Implement "sort" endpoint for reordering folder contents
see related issue here https://github.com/plone/volto/issues/940

### PR DESCRIPTION
**Pull request by petschki**
fixes #812 
related https://github.com/plone/volto/issues/940

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by lukasgraf** [comment]
As per my comment in plone/volto#940: Is the intent of those user interface actions really to persistently change the sort order of items in the DB, not just affect query sorting? It seems strange to me, but to be honest it's been quite a while since I just a plain out-of-the-box folder contents view, so just wanting to make sure :wink:

Please also note that there is currently a [discussion in the @plone/restapi-team](https://github.com/orgs/plone/teams/restapi-team/discussions/1) on whether we want to move ordering functionality to a dedicated `@order` endpoint, instead doing it via the pseudo-field `ordering`. If we were to to that, this one should obviously be in the same style (so a `@sort` endpoint). We should therefore conclude that discussion before merging this one.

**Comment by petschki** [comment]
Thanks for the pointer to the discussion. apart from the UI point of view in volto I think we should provide a rearrange action here.

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@petschki sorry it took so long to review and merge your PR. Will do a release in the next days...

**Pull request merged**
