### PR TITLE
Return widget info for boolean fields

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@MrTango can you elaborate on why you/we need to return the "widget" value in addition to the "type" value we already provide? I mean the frontend can render a boolean widget based on the "type" value. This is what we do in Volto.

**Comment by MrTango** [comment]
@tisto maybe talk to @robgietema he needs to do a lot of mapping on the client side, because of this missing information. The field type is not always enougth.

**Comment by tisto** [comment]
@MrTango I talk to @robgietema on a daily basis and I still don't understand why we need to duplicate the information. There is no other option for boolean fields, so what additional information will a "widget" field provide with the same value?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
