### PR TITLE
[WIP] Fix json serialization of dexterity validation errors.

### PR DESCRIPTION
**Pull request by tdesvenain**
Make consistent with https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/content/utils.py#L30

### CODE REVIEW

**Comment by tisto** [comment]
@tdesvenain thanks for the fix! I think we have to go over all our error messaging and make it more consistent...this has been on my todo list for quite a while. Any kind of help is appreciated. :)

**Comment by tisto** [comment]
@tdesvenain there are a few static code analysis violations:

```
Flake8..........................[ FAILURE ] in 6.028s
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/dxcontent.py:78:80: E501 line too long (96 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/dxcontent.py:81:80: E501 line too long (94 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/dxcontent.py:105:80: E501 line too long (94 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/dxcontent.py:113:80: E501 line too long (92 > 79 characters)
The command "bin/code-analysis" exited with 1 in 6.028s.
```

**Comment by tdesvenain** [comment]
We may have a talk on issue on https://github.com/plone/plone.restapi/issues/496 before i merge this, may we ?
I agree with you about error messaging. I wrote error handling of `@plone/restapi-angular` and i got pain.

https://github.com/plone/plone.restapi-angular/blob/master/src/services/authentication.service.ts#L154

Having consistent error api would be fine. But `plone.rest` product is concerned. i don't know where we should begin.

**Comment by tisto** [comment]
@tdesvenain what shall we do here now? Do you want to rebase and we merge or shall we wait until #496 is fully resolved?

**Comment by tisto** [comment]
@tdesvenain any updates here? If this includes breaking changes, the time to discuss this is now, since I plan to do a 2.0.0 in the next days.

**Comment by jensens** [comment]
is this still valid?

**Pull request closed without merging**
