### PR TITLE
add available languages information to the @site endpoint

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
My initial idea was to allow Volto to get multilingual settings from the configuration at the backend, see https://github.com/plone/volto/pull/5506

There are some challenges there though.

In any case, I think that it would be a great addition to the rest api.

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
