### PR TITLE
Fix for #676 in workflow service.

### PR DESCRIPTION
**Pull request by zopyx**
Python 3 incompatibility fixed

### CODE REVIEW

**Comment by Rotonen** [comment]
@jenkins-plone-org please run jobs

**Comment by zopyx** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@zopyx thanks for the fix! Were you be able to figure out why we use/need the "decode('utf-8')" in Python 2? We might want to add a comment in the code to make it more obvious why this is necessary.

**Comment by tisto** [comment]
We are also kind of missing a unit test that should have cached this in the first place.

**Comment by tisto** [comment]
@zopyx there are some code-analysis violations. Would you mind having a look?

**Comment by zopyx** [comment]
> @zopyx there are some code-analysis violations. Would you mind having a look?

Done

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
