### PR TITLE
Add a converter for Decimal() objects.

### LINKED ISSUE #963: Missing converter for Decimal()
I have a content type containing a Decimal field defined as:

```
    hike_distance = schema.Decimal(
        title=_(u'Distance'),
        description=u'''
        ''',
        min=Decimal(0),
        required=False,
    )
```

When I try to request objects of this content type directly or with `fullobjects` or with `metadata_fields=hike_distance`, I get an error `TypeError: No converter for making Decimal('12') (<class 'decimal.Decimal'>) JSON compatible.`

Indeed, as the error says, there is no converter for Decimal even though it is [documented](https://plonerestapi.readthedocs.io/en/latest/types-schema.html#decimal).  Moreover, the serializer test for Decimal seems to be incorrect, as it merely serializes a string instead of a Decimal object.

### PR DESCRIPTION
**Pull request by fulv**
Fixes #963

### CODE REVIEW

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
The only test failure is with Python 3.7 (none of the other Python version) and has to do with black.  I can't reproduce this.

**Comment by tisto** [comment]
@fulv you have to run black on your PR. We run black only for the Python 3.7 / Plone 5.2 job. Here is the output in Travis of the line that fails:

````
The command "if [ "$PLONE_VERSION" == "5.2.x" ] && [ $TRAVIS_PYTHON_VERSION == '3.7' ]; then pip install black && black src/ --check; fi" exited with 1.
````

Just run:

````
bin/black src/
````

and you are good.

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

robot tests...

**Comment by tisto** [comment]
Thanks @fulv!

**Pull request merged**
