### PR TITLE
Fix the category of the 'Users and groups settings' controlpanel adapter

### PR DESCRIPTION
**Pull request by sneridagh**
Fixes: #1482

### CODE REVIEW

**Comment by ksuess** [comment]
This is /controlpanel
What's wrong on your side? Please provide some more info here or in an issue.
image

**Comment by ksuess** [comment]
> This is /controlpanel 

backend Plone 6 current beta
frontend Volto branch master

**Comment by sneridagh** [comment]
@ksuess my bad, I documented it in the issue: https://github.com/plone/plone.restapi/issues/1482

**Comment by ksuess** [comment]
I put an effort to get things right when adding the group membership control panel. But, yes, will check what's going wrong.

**Comment by sneridagh** [comment]
Volto side fix: https://github.com/plone/volto/pull/3603

**Comment by sneridagh** [comment]
> I put an effort to get things right when adding the group membership control panel. But, yes, will check what's going wrong.

All good, as said, it seems that the category was not ok. TBH I've been there as well, the mapping between classic and restapi handling is not intuitive and error prone. :(

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Review by ksuess — APPROVED** [review]

**Pull request merged**
