### PR TITLE
Check that we are in Plone 5 in content-adding endpoint if p.a.multilingual is installed

### PR DESCRIPTION
**Pull request by erral**
See #1029 for reference

@libargutxi

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@erral what version of `plone.app.multilingual` are you using? I am using version 2.0.4 in Plone 4.3 and the `ITranslationManager` is in the location used by plone.restapi:

https://github.com/plone/plone.app.multilingual/blob/2.0.4/src/plone/app/multilingual/interfaces.py#L82

**Review by avoinea — APPROVED** [review]
LGTM

**Comment by erral** [comment]
@wesleybl we are using plone.app.multilingual 1.x and in that version the import should be done from plone.multilingual.

Anyway the plone.app.multilingual support in plone.restapi is only for Plone 5, due to several import location changes and dependencies of different Plone versions. I remember it because I was the one who took that decision :smile: 

We wrote other packages to provide plone.app.multilingual and Products.LinguaPlone compatibility for Plone 4.3.x named collective.restapi.pam and collective.restapi.linguaplone

**Comment by erral** [comment]
@wesleybl FWIW see https://github.com/plone/plone.restapi/issues/225#issuecomment-298526226

**Comment by tisto** [comment]
@erral thanks Mikel! Is that something we would like to backport to 6.x.x?

**Comment by erral** [comment]
Yes, we would need it to be in the 6.x branch because it's needed in Plone 4.3.x Thanks!

**Comment by tisto** [comment]
@erral ok, I will clean up the 6.x.x branch, fix Travis, move to gh actions and then merge this PR and do a release.

**Pull request merged**
