### PR TITLE
Make types endpoint return 'string' for the widget attribute by default.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@ebrehault I would like to hear your opinion before I put effort into adapting our tests to pass. Would you be ok if we would always include the widget attribute and make "string" the default value for it?

**Comment by ebrehault** [comment]
@tisto why do you think it is better to do provide a default widget in the schema rather than let the mechanism in charge of rendering the form to choose by itself a default widget if none is provided in the schema? (I don't say I am opposed to your change, I am just curious)

**Comment by tisto** [comment]
@ebrehault it was actually a request made by my front end devs. I think whatever we choose to do, we should try to be consistent. So here are the options (in general):

1) Always show all possible fields and force a default value
2) Always show all possible fields and allow None as a value
3) Omit fields that don't have a value set

We currently do 3) here but not for other endpoints (e.g. content). I need to investigate this a bit further, but I think we currently do 2). If this is the case we should do the same here as well (and not use the first option that I proposed initially).

**Comment by ebrehault** [comment]
+1 for consistency, and my preference would either 1 or 3 (I think 2 is quite useless)

**Comment by tisto** [comment]
@ebrehault could you elaborate why you think 2) is useless? I would say this is what we currently do for the content endpoint. We iterate over existing the attributes (zope schema, behaviors, etc.) and then show None if there is no value set (and no default value defined, which can be the case). This matter is also related to the question how we represent null values in plone.restapi: https://github.com/plone/plone.restapi/issues/187

**Comment by ebrehault** [comment]
@tisto if we have:
```json
{"id": 12, "title": "my title", "subjects": null}
```
or:
```json
{"id": 12, "title": "my title"}
```
This code will work the same with both:
```javascript
.subscribe(response => {
    if(!response.subjects) { ... }
});
```
but the second is shorter and easier to read.

**Comment by tisto** [comment]
@ebrehault convinced me. Will close this pr.

**Pull request closed without merging**
