### PR TITLE
Fix AttributeError REQUEST in linkintegrity when pasting nested content

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/plone/plone.restapi/issues/1536

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@wesleybl Can you check that this helps? I did not try it.

@tisto This would be good to have in a release. I want rc1 this Friday.

**Review by tisto — APPROVED** [review]
LGTM!

**Comment by tisto** [comment]
CI fails because of a failing version comparison in the rest api response:

````
diff --git a/src/plone/restapi/tests/http-examples/translated_messages_addons.resp b/src/plone/restapi/tests/http-examples/translated_messages_addons.resp
index 5af758c..bc473c3 100644
--- a/src/plone/restapi/tests/http-examples/translated_messages_addons.resp
+++ b/src/plone/restapi/tests/http-examples/translated_messages_addons.resp
@@ -73,7 +73,7 @@ Content-Type: application/json
                 "newVersion": "0006",
                 "required": false
             },
-            "version": "8.32.1.dev0"
+            "version": "8.32.2.dev0"
         },
         {
             "@id": "http://localhost:5[50](https://github.com/plone/plone.restapi/actions/runs/3492591267/jobs/5846533028#step:11:51)01/plone/@addons/plone.session",
````

Will merge this and fix in main.

**Review by wesleybl — COMMENTED** [review]
I tested it and that fixed the problem.

Thanks!

**Pull request merged**
