### PR TITLE
Further normalise http-examples, and no port hardcoding

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This is for master what I already [did on 7.x.x](https://github.com/plone/plone.restapi/pull/1218#pullrequestreview-754383233).

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by wesleybl — APPROVED** [review]

**Comment by tisto** [comment]
@mauritsvanrees could you rebase your PR please? Why am I missing the port normalization code in this PR that I saw in the other one? The CI jobs are green, is this code already in master?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees could you rebase your PR please?

Done.

> Why am I missing the port normalization code in this PR that I saw in the other one? The CI jobs are green, is this code already in master?

The port normalisation on master was done and merged in PR #1215.
It was backported to 7.x.x in PR #1218, but after feedback from @wesleybl I did a few more changes there.
The current PR is a forward port of those few final fixes.
So it is still needed.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
