### PR TITLE
Update plone 6a2

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@tisto @jensens what's the trick to make it work in both 5 and 6? I tried it up and keeps breaking.

I saw that @ericof is using pip and a custom GH action in https://github.com/plone/plone.volto/blob/main/.github/workflows/tests.yml

**Comment by jensens** [comment]
Buildout still works fine. We better should depend on released constraints, so we are in sync. I dont understand the comment `# Keep this file in sync with: https://github.com/kitconcept/buildout/edit/master/requirements.txt` - I think this is historical and must be changed, since we are in Plone core know.

**Comment by sneridagh** [comment]
@jensens agreed, but how to maintain both builds working with the same requirements/constraints? any pointer?

**Comment by jensens** [comment]
> how to maintain both builds working with the same requirements/constraints?

Impossible. One need to point to `https://dist.plone.org/release/5.2-latest/[versions.cfg|constraints.txt|requirements.txt]`, the other to `https://dist.plone.org/release/6.0[a2|-dev]/*`.

**Comment by sneridagh** [comment]
Superseded by #1314

**Pull request closed without merging**
