### PR TITLE
Add missing id to the Plone site serialization, related to issue #186

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by lukasgraf** [comment]
@sneridagh can you add a changelog entry please? Also I think some tests might fail because of changed data in the `docs/source/_json` files 😉

**Comment by sneridagh** [comment]
@lukasgraf True! I will take care

**Comment by sneridagh** [comment]
@lukasgraf done!

**Comment by lukasgraf** [comment]
@sneridagh 🎉 💚 🍰

**Pull request merged**
