### PR TITLE
Add test that tests the redirector behavior of plone.restapi

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@ericof @sneridagh I wrote a test to prove that plone.restapi behaves in a wrong way when re-using a plone.app.redirector redirect. Though, it turns out the test passed. I just proved that it also works like this in real life. I have no clue why this didn't work before.

**Comment by ericof** [comment]
@tisto I "fixed" the test, now it proves there is an infinite loop

**Comment by ericof** [comment]
A PR is open on [plone.rest](https://github.com/plone/plone.rest/pull/134)

**Comment by sneridagh** [comment]
@tisto released it, however, then should we make p.restapi depend on p.rest 2.0.0a5 as minimum requirement?

**Comment by ericof** [comment]
@sneridagh Plone 6 should depend on p.rest 2.0.0a5, right?

**Comment by tisto** [comment]
@sneridagh @ericof I'd prefer to avoid hard requirements in setup.py. They cause lots of trouble for everyone who is using buildout. I'd prefer to pin the newer versions in our buildout and in the released Plone versions.

**Comment by tisto** [comment]
@sneridagh @ericof I am totally out of the loop here. Is that test something we want in plone.restapi or shall we close the issue?

**Comment by davisagli** [comment]
@tisto The issue was fixed in plone.rest and a similar test added there. I don't think we need a copy of the test here.

**Pull request closed without merging**
