### PR TITLE
[WIP] dxcontent: add targetUrl for primary file fields

### PR DESCRIPTION
**Pull request by csenger**
https://github.com/plone/plone.restapi/issues/886

### CODE REVIEW

**Comment by sneridagh** [comment]
@carsten targetUrl it is then?

**Comment by csenger** [comment]
> @carsten targetUrl it is then?

@sneridagh Yes, it is. 

The logic in the endpoint now mirrors the behavior implemented in plone 4. It adds targetUrl only if the user is not able to edit the content. That is the behavior I talked about with Rob and I think it is convenient for Volto (as it directly fits the use case). Though while implementing it I not sure it is the best implementation for the API. For a more generic use we'd have to add that url every time and name the primary field.

We can't just add that info to the file field object as there is a second use case for link types where the remoteUrl should be used, but this is not an object but a string

So we might want to add an extra property in the future regardless of the edit permission like 

```
primaryField: {
  name: "file",
  target: "http://...."
}
```

Please review the PR.

**Comment by tisto** [comment]
@sneridagh this is what we agreed upon, right?

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
