### PR TITLE
In Plone 6, uses plone.textindexer to add block texts to the SearchableText index

### LINKED ISSUE #1744: IBlocks SearchableText indexer bypasses plone.textindexer behavior
The `SearchableText_blocks` indexer combines searchable text from blocks with the result of calling the base searchable text extractor, which is hardcoded to be `plone.app.contenttypes.indexers.SearchableText`. However, if the `plone.textindexer` behavior is active, it will be bypassed by this, so `IDynamicTextIndexExtender` adapters won't be used.

Given the way the component architecture handles adapter lookups, there may be no clean solution to call "whatever would have been called for a searchable text indexer if the `IBlocks` one wasn't in place". Another solution would be to turn the logic upside-down and implement the `IBlocks` indexer as an `IDynamicTextIndexExtender` adapter, which would require the `plone.textindexer` behavior to be implied by using Blocks.

I'm not sure what the best or cleanest solution might be. However, Blocks competing with `plone.textindexer` for the actual indexer feels unexpected and possible solutions feel hacky.

### PR DESCRIPTION
**Pull request by wesleybl**
This ensures that behaviors can add fields to SearchableText with `plone.textindexer`.

`IBlocks` now inherits from `IDexterityTextIndexer`, so there is no need to add the `plone.textindexer` behavior to the types to enable indexing. The content simply needs to have the `IBlocks` behavior.

fixes #1744

### CODE REVIEW

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@davisagli is it necessary to remove the Plone Jenkins CI job - pull-request-6.1-3.8 from the repository configuration?

**Review by davisagli — APPROVED** [review]
@wesleybl This looks good. I made a couple simplifications to the conditional imports -- see what you think.

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
> I made a couple simplifications to the conditional imports -- see what you think.

@davisagli better. Thanks!

**Pull request merged**
