### PR TITLE
Use /en as the default redirect

### PR DESCRIPTION
**Pull request by stevepiercy**
See https://github.com/plone/plone.restapi/pull/1337#pullrequestreview-929571301

### CODE REVIEW

**Comment by tisto** [comment]
@stevepiercy as long as we have a red build, we can not merge any PR. We can either stop testing Plone 6 altogether (and then merge this PR) or find a fix. I haven't touched mockup ever in my Plone career and I am absolutely clueless why the build started to fail.

**Comment by stevepiercy** [comment]
@tisto the clueless leading the clueless! 😉  I know even less than you do. I would defer to the maintainers for advice on how to proceed.

**Comment by tisto** [comment]
@stevepiercy I am currently not even able to build Plone 6 on my local machine due to zc.buildout issues. I have been able to test against multiple Plone versions since > 5 years now. Though, the changes in Plone 6 make it very very hard to keep up with that.

**Comment by stevepiercy** [comment]
@tisto it looks like @mauritsvanrees proposed a fix in https://github.com/plone/plone.restapi/pull/1356. Would you please review that PR? 

If it is merged, then I can merge master to this branch, or rebase this branch on master, whichever is preferable, and push.

**Comment by tisto** [comment]
@stevepiercy I merged Maurits' PR. If you merge master into your branch it should be green now.

**Comment by mauritsvanrees** [comment]
Meanwhile it will break again, because the plone.base PLIP was merged. I will make a PR to unbreak it.

**Comment by mauritsvanrees** [comment]
See https://github.com/plone/plone.restapi/pull/1358

**Comment by stevepiercy** [comment]
Restarted one failed [build (3.7, 6.0)](https://github.com/plone/plone.restapi/runs/5858983277?check_suite_focus=true#logs), in case it was a temporary thing.

**Comment by stevepiercy** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
Can I get a review, please? All green!

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
