### PR TITLE
Use json_compatible when serializing users

### LINKED ISSUE #1493: User with datetime schema field is not serialized correctly
If you add a datetime field to a userschema, it is saved as a "DateTime" object, but if later you request to serialize that object you get a "Datetime object is not JSON serializable" error.

The point is that the @users endpoint doesn't convert the values to JSON compatible values using the existing json_compatible function.

### PR DESCRIPTION
**Pull request by erral**
Fixes #1493 

cc: @ionlizarazu

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@erral this does relate to: https://github.com/plone/plone.restapi/pull/707?

**Comment by erral** [comment]
It is related. We do not need it in the context of #707 but it will be useful there too.

We reached to the current issue when adding a DateTime field in the user schema.

**Pull request merged**
