### PR TITLE
Control panels: Dexterity Content Types

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by jensens** [comment]
Meta: 
- Use Labels
- Use Draft Pull Requests
- Do not use the Title.

I fixed that.

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@avoinea Travis fails with two changes in the documentation. No idea where they come from. If we fix the CI and add some unit/integration tests for the new control panel, we can merge and release it.

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@avoinea oh, cool. you fixed the issues that my tests found :)

Let's wait for Jenkins and Travis and then merge and release!

**Comment by tisto** [comment]
ok, seems we have some hard-coded portal_url in our code...

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@tisto Somehow we missed the CHANGELOG :smile:

**Comment by avoinea** [comment]
A, sorry, you moved them to news for `towncrier`

**Pull request merged**
