### PR TITLE
Add support for IContextSourceBinder vocabularies on JSON schema Choi…

### PR DESCRIPTION
**Pull request by sneridagh**
…ce fields adapters.

### CODE REVIEW

**Comment by sunew** [comment]
it would be good with a unit test with realistic vocab titles - Føø bär perhaps?

**Comment by sunew** [comment]
I currently have a bug with vocabs with non-ascii titles - working on a PR - this will extend the tests.

**Comment by jaroel** [comment]
@sunew That sounds out of scope for this PR.
Could you fix a new issue for the vocab problems, thanks!

**Comment by tisto** [comment]
@sunew is that a general problem with non-ascii titles in vocabularies or just a problem with this particular pr?

**Comment by sunew** [comment]
@tisto @jaroel general problem. I'm working on a failing test + new PR

**Pull request merged**
