### PR TITLE
Test showing the difference

### PR DESCRIPTION
**Pull request by sneridagh**
The test fails right now.

### CODE REVIEW

**Comment by davisagli** [comment]
@wesleybl Then shouldn't we merge the test, to make sure there isn't a future regression, instead of closing the PR?

**Comment by wesleybl** [comment]
@davisagli Okay. I made some fixes.

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@sneridagh @davisagli can you merge this PR please? I think Plone 6.1 is no longer tested with Python 3.8 in Jenkins.

**Comment by davisagli** [comment]
@wesleybl I updated the repository's branch protection rules so that it requires the Plone 6.1 + Python 3.10 build instead of Python 3.8.

**Pull request merged**
