### PR TITLE
Fix of users endpoint for Membrane users.

### PR DESCRIPTION
**Pull request by ksuess**
acl_users.searchUsers fails for id=None

Fix https://github.com/plone/plone.restapi/issues/1459

### CODE REVIEW

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
Unrelated test failure

**Comment by ksuess** [comment]
once again! @jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@plone/ai-team, I have still unrelated test failures. Can you throw an eye on it, please.

**Review by davisagli — APPROVED** [review]
LGTM

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

Unstable failing robot test is indeed unrelated. I have opened an issue: https://github.com/plone/Products.CMFPlone/issues/3582

**Pull request merged**
