### PR TITLE
Add adapter for IBytes for JSONFieldSchema generator to support Named…

### PR DESCRIPTION
**Pull request by sneridagh**
…File objects.

### CODE REVIEW

**Comment by sneridagh** [comment]
Related to issue #254

**Comment by tisto** [comment]
@lukasgraf @buchi I know you guys are quite busy these days. Though, unfortunately we are under a lot of time pressure right now. It would be great if you could have a quick look. If not I would merge this pr later  today or tomorrow morning. Looks all good to me.

**Comment by lukasgraf** [comment]
@tisto yeah, busy as hell and also under time pressure. But so are you guys, so just keep poking me if I miss something that you need to get moved along quickly 👍

**Comment by sneridagh** [comment]
@lukasgraf Thanks a lot!! 🎉

**Pull request merged**
