### PR TITLE
cd src && find . -name "*.py"|xargs pyupgrade --py36-plus

### PR DESCRIPTION
**Pull request by jensens**
1. `cd src && find . -name "*.py"|xargs pyupgrade --py36-plus` (see https://github.com/asottile/pyupgrade)
2. run `black .`
3. manual remove six imports which are no longer needed

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Note to self: Next time do not manual remove six import leftovers, but use `pycln`.

**Comment by ericof** [comment]
LGTM

**Review by ericof — APPROVED** [review]

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Pull request merged**
