### PR TITLE
Centralize logic for finding all blocks

### PR DESCRIPTION
**Pull request by davisagli**
Add a `visit_blocks` util which can be extended using IBlockVisitor subscribers.

To do:
- [x] Add visit_blocks
- [x] Use visit_blocks for serialization and deserialization
- [x] Use visit_blocks for linkintegrity
- [x] Use visit_blocks to collect searchable text for blocks
- [x] Implement IBlockVisitor for nested `blocks`
- [x] Implement IBlockVisitor in plone.volto for nested `columns`, `hrefList`, and `slides` -> https://github.com/plone/plone.volto/pull/127
- [x] test for visiting sub-blocks first
- [x] docs

This should also be useful for https://github.com/plone/plone.volto/pull/121

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@plone/volto-team This is some refactoring to reduce code duplication and provide a standard way to get all blocks (including blocks contained inside another block). I think it is backwards-compatible; do you see any problem?

**Review by stevepiercy — APPROVED** [review]
Docs look good. Thank you!

**Review by sneridagh — APPROVED** [review]
LGTM! 🎉

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
