### PR TITLE
Return proper error message when trying to create a content object wi…

### PR DESCRIPTION
**Pull request by tisto**
…th a wrong @type parameter.

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@plone/restapi-team Can we have a new release please for Plone 6?
This PR from February is in fact the only code change. The rest are changes in test setup and docs.

I might just release Plone 6 alpha 4 tonight. I feel lucky. So I might make the release myself. Sorry for the short notice!

**Comment by mauritsvanrees** [comment]
I have released `plone.restapi` 8.22.0.

**Pull request merged**
