### PR TITLE
@rules endpoint

### PR DESCRIPTION
**Pull request by avoinea**
See #1397 and #324

### CODE REVIEW

**Comment by fredvd** [comment]
As mentionned at the Volto team meeting tuesday 7th, 'we' are aware of the recent testing issues. These are unstable robottests that fail occasionally that crept into core and where a problem with the reporting let the number increase too much before we noticed them.  And then it became a situation of always some (and too many) seemingly random tests failing, but it was always a subset. 

We're almost back to zero failing tests most of the runs, I manually started the pull-request-6.0-3.8 yesterday evening, which we have modfied locally on jenkins to only run robot tests and with some other tweaks/experiments to improve the overall tests.   I'll get back to this PR when we are finished and run the jobs again.

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
To be continued https://github.com/plone/plone.restapi/pull/1496

**Pull request closed without merging**
