### PR TITLE
Plip #3279

### PR DESCRIPTION
**Pull request by tisto**
see plone/Products.CMFPlone#3279

### CODE REVIEW

**Comment by tisto** [comment]
Just for reference the passing tests with this PR in buildout.coredev:

````
buildout.coredev-6.0 git:(6.0) ✗ bin/test -s plone.restapi
/Users/timo/workspace/plone/buildout.coredev-6.0/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py:273: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/Users/timo/workspace/plone/buildout.coredev-6.0/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/Users/timo/workspace/dotfiles/.buildout/eggs/robotframework-3.1.2-py3.8.egg/robot/utils/robottypes3.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, UserString
/Users/timo/workspace/dotfiles/.buildout/eggs/robotframework-3.1.2-py3.8.egg/robot/utils/normalizing.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import MutableMapping
/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/testing.py:148: DeprecationWarning: ZSERVER_FIXTURE is deprecated. Please import from plone.testing.zope.
  bases=(PLONE_RESTAPI_DX_FIXTURE, z2.ZSERVER_FIXTURE),
/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/tests/test_documentation.py:30: DeprecationWarning: Browser is deprecated. Please import from plone.testing.zope.
  from plone.testing.z2 import Browser
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
    3/59 (5.1%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/serializer/expansion.py:13: DeprecationWarning: ``expand`` as a string parameter separated with commas is deprecated and will be removed in plone.restapi 9.0. Use ``expand:list`` instead.
  warnings.warn(

  Ran 59 tests with 0 failures, 0 errors, 0 skipped in 0.029 seconds.
Running plone.restapi.testing.PloneRestApIBlocksLayer:Integration tests:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
  Set up plone.restapi.testing.DateTimeFixture in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.zope.Startup in 0.059 seconds.
  Set up plone.app.testing.layers.PloneFixture Could not install product Products.CMFFormController
in 2.181 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.075 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.111 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayer /Users/timo/workspace/plone/buildout.coredev-6.0/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/Users/timo/workspace/dotfiles/.buildout/eggs/plone.behavior-1.4.0-py3.8.egg/plone/behavior/metaconfigure.py:170: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/testing.py:121: DeprecationWarning: installProduct is deprecated. Please import from plone.testing.zope.
  z2.installProduct(app, "plone.restapi")
in 0.197 seconds.
  Set up plone.restapi.testing.PloneRestApIBlocksLayer in 0.023 seconds.
  Set up plone.restapi.testing.PloneRestApIBlocksLayer:Integration in 0.000 seconds.
  Running:

  Ran 14 tests with 0 failures, 0 errors, 0 skipped in 0.956 seconds.
Running plone.restapi.testing.PloneRestApiDXLayer:Integration tests:
  Tear down plone.restapi.testing.PloneRestApIBlocksLayer:Integration in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApIBlocksLayer in 0.002 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayer:Integration in 0.000 seconds.
  Running:
    32/410 (7.8%)/opt/homebrew/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:1215: DeprecationWarning: assertDictContainsSubset is deprecated
  warnings.warn('assertDictContainsSubset is deprecated',
    259/410 (63.2%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.scale/plone/scale/scale.py:141: DeprecationWarning: the 'direction' option is deprecated, use 'mode' instead
  warnings.warn(

  Ran 410 tests with 0 failures, 0 errors, 7 skipped in 17.172 seconds.
Running plone.restapi.testing.PloneRestApiTestWorkflowsLayer:Integration tests:
  Tear down plone.restapi.testing.PloneRestApiDXLayer:Integration in 0.000 seconds.
  Set up plone.restapi.testing.PloneRestApiTestWorkflowsLayer in 0.025 seconds.
  Set up plone.restapi.testing.PloneRestApiTestWorkflowsLayer:Integration in 0.000 seconds.
  Running:

  Ran 21 tests with 0 failures, 0 errors, 0 skipped in 0.914 seconds.
Running plone.restapi.testing.PloneRestApiDXPAMLayer:Integration tests:
  Tear down plone.restapi.testing.PloneRestApiTestWorkflowsLayer:Integration in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApiTestWorkflowsLayer in 0.002 seconds.
  Tear down plone.restapi.testing.PloneRestApiDXLayer in 0.002 seconds.
  Set up plone.restapi.testing.PloneRestApiDXPAMLayer in 0.508 seconds.
  Set up plone.restapi.testing.PloneRestApiDXPAMLayer:Integration in 0.000 seconds.
  Running:

  Ran 3 tests with 0 failures, 0 errors, 0 skipped in 0.278 seconds.
Running plone.restapi.testing.PloneRestApIBlocksLayer:Functional tests:
  Tear down plone.restapi.testing.PloneRestApiDXPAMLayer:Integration in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApiDXPAMLayer in 0.001 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayer in 0.136 seconds.
  Set up plone.restapi.testing.PloneRestApIBlocksLayer in 0.022 seconds.
  Set up plone.testing.zope.WSGIServer in 0.018 seconds.
  Set up plone.restapi.testing.PloneRestApIBlocksLayer:Functional in 0.000 seconds.
  Running:

  Ran 3 tests with 0 failures, 0 errors, 0 skipped in 0.475 seconds.
Running plone.restapi.testing.PloneRestApiDXLayer:Functional tests:
  Tear down plone.restapi.testing.PloneRestApIBlocksLayer:Functional in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApIBlocksLayer in 0.001 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayer:Functional in 0.000 seconds.
  Running:
    113/556 (20.3%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/serializer/expansion.py:13: DeprecationWarning: ``expand`` as a string parameter separated with commas is deprecated and will be removed in plone.restapi 9.0. Use ``expand:list`` instead.
  warnings.warn(
    185/556 (33.3%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/serializer/vocabularies.py:47: DeprecationWarning: ``token`` parameter is deprecated and will be removed in plone.restapi 9.0. Use ``tokens`` parameter instead.
  warnings.warn(
    190/556 (34.2%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/services/history/get.py:74: DeprecationWarning: an integer is required (got type DateTime).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["time"] = dt.fromtimestamp(item["time"]).isoformat()
    421/556 (75.7%)/Users/timo/workspace/plone/buildout.coredev-6.0/src/plone.restapi/src/plone/restapi/services/tiles/get.py:36: DeprecationWarning: ``plone.restapi.services.tiles`` is deprecated and will be removed in plone.restapi 9.
  warnings.warn(

  Ran 556 tests with 0 failures, 0 errors, 6 skipped in 57.882 seconds.
Running plone.restapi.testing.PloneRestApiDXPAMLayer:Functional tests:
  Tear down plone.restapi.testing.PloneRestApiDXLayer:Functional in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApiDXLayer in 0.001 seconds.
  Set up plone.restapi.testing.PloneRestApiDXPAMLayer in 0.437 seconds.
  Set up plone.restapi.testing.PloneRestApiDXPAMLayer:Functional in 0.000 seconds.
  Running:

  Ran 27 tests with 0 failures, 0 errors, 0 skipped in 4.084 seconds.
Running plone.restapi.testing.PloneRestApiDXIterateLayer:Functional tests:
  Tear down plone.restapi.testing.PloneRestApiDXPAMLayer:Functional in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApiDXPAMLayer in 0.001 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.018 seconds.
  Tear down plone.restapi.testing.DateTimeFixture in 0.000 seconds.
  Set up plone.app.iterate.testing.DexPloneAppIterateLayer in 0.087 seconds.
  Set up plone.restapi.testing.PloneRestApiDXIterateLayer in 0.051 seconds.
  Set up plone.restapi.testing.PloneRestApiDXIterateLayer:Functional in 0.000 seconds.
  Running:

  Ran 13 tests with 0 failures, 0 errors, 0 skipped in 1.473 seconds.
Tearing down left over layers:
  Tear down plone.restapi.testing.PloneRestApiDXIterateLayer:Functional in 0.000 seconds.
  Tear down plone.testing.zope.WSGIServer in 0.001 seconds.
  Tear down plone.restapi.testing.PloneRestApiDXIterateLayer in 0.001 seconds.
  Tear down plone.app.iterate.testing.DexPloneAppIterateLayer in 0.018 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.002 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.017 seconds.
  Tear down plone.testing.zope.Startup in 0.002 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.
Total: 1106 tests, 0 failures, 0 errors, 13 skipped in 1 minutes 28.411 seconds
````

**Comment by ale-rt** [comment]
I am running the jenkins job manually with this parameters:
```
https://github.com/plone/Products.CMFPlone/pull/3450
https://github.com/plone/plone.restapi/pull/1341
```

**Comment by ale-rt** [comment]
This will break the 5.2 build:
```
Error: Picked: plone.autoinclude = 1.0.0a4
```
I will make a PR yo add `plone.autoinclude = 1.0.0a4` in to the 5.2 buildout coredev and then retry it

**Comment by ale-rt** [comment]
Oh I am stupid... of course the 5.2 jobs should not run https://github.com/plone/Products.CMFPlone/pull/3450...

**Review by ale-rt — APPROVED** [review]

**Comment by ale-rt** [comment]
@tisto, @plone/restapi-team  I merged plone/Products.CMFPlone#3450, can you merge this

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I merge this, to fix Jenkins on Plone 6.

**Pull request merged**
