### PR TITLE
Black

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by sneridagh** [comment]
@tisto if we do this, don’t we have to switch development to Python3/Plone 5.2 as well? Black does not work in 2.7.

**Comment by erral** [comment]
Black runs on python3 but it also formats python2 code https://github.com/ambv/black#installation

**Comment by tisto** [comment]
FYI: I just wanted to give black a shot. I'd merge this PR once Plone 5.2 is out and Python 3 is kind of the new default/standard. There is no need to rush with that.

**Comment by Rotonen** [comment]
You should simply any disable line length checks in any other linter you happen to use as black is not hard limited to 88 characters per line.

**Comment by tisto** [comment]
@Rotonen can you elaborate on that? Here is what I found in the black docs:

> If you're using Flake8, you can bump max-line-length to 88 and forget about it.

https://github.com/python/black#line-length

**Comment by Rotonen** [comment]
This is what Black itself says in its readme:
https://github.com/python/black#line-length

> Black will try to respect that. However, sometimes it won't be able to without breaking other rules. In those rare cases, auto-formatted code will exceed your allotted limit.

I've also hit this in practice. If you use black, just let it do its thing within the domain of line lenghts and disable the line length nagging in all other tools as they're now unnecessary and sometimes wrong.

**Comment by tisto** [comment]
@Rotonen would you mind sharing your .flake8 config? I still run into issues with using black's gh repo version.

**Comment by tisto** [comment]
Closing in favor of https://github.com/plone/plone.restapi/pull/734

**Comment by Rotonen** [comment]
I use [pylama](https://github.com/klen/pylama), which does about the same as flake8, but I prefer the unified interface of inputs and outputs it provides for me. They both wrap about the same linters and you can configure them both in about the same way in either `setup.cfg` or in their own config files (or soon enough in `pyproject.toml`).

We have a different styleset internally, as we allow up to 125 long lines (max Github diff width), but prefer for people to try to stay within 80, if sensibly doable.

Most of the stuff I have on locally does not trip up on the CI. I mostly use that stuff, especially pylint warnings, as guidelines of having done something new in an unclean way. A good example would be modifying the method signature of something you're overriding.

But here is my `pylama.ini` for Plone 4.3 projects:

```
[pylama]
linters = pycodestyle,pydocstyle,pyflakes,pylint,eradicate
ignore = C0103,C0111,C0302,C0330,C0411,C0412,D100,D102,D105,D107,D203,D213,E0611,E1101,E1102,E1121,E1133,R0901,R0902,R0903,R0904,R0913,R0914,R0915,R1702

# C0103 - We do not enforce module scope constants to be uppercase
# C0111 - We do not enforce module scope docstrings
# C0302 - We do not enforce line number limits for modules
# C0330 - This collides with black and is a known pylint bug: https://github.com/PyCQA/pylint/issues/289
# C0411 - We do a simple flat sort of imports
# C0412 - We do a simple flat sort of imports
#  D100 - We do not enforce docstrings on the module scope
#  D102 - We do not enforce docstrings on public methods
#  D105 - We do not enforce docstrings on magic methods
#  D107 - We do not enforce docstrings in __init__
#  D203 - We rather have the mandatory newline after a docstring
#  D213 - We rather have the mandatory newline after a docstring
# E0611 - Zope interfaces confuse module member checking
# E1101 - Zope interfaces confuse object member checking
# E1102 - Zope interfaces confuse callability checking
# E1121 - Zope interfaces confuse argument count checking
# E1133 - Zope interfaces confuse iterability checking
# R0901 - Zope inheritance hierarchies are too deep to limit ancestor count
# R0902 - We do not enforce instance member count limits
# R0903 - We do not enforce minimum public method counts
# R0904 - We do not enforce public method count limits
# R0913 - We do not enforce argument count limits
# R0914 - We do not enforce local variable count limits
# R0915 - We do not enforce scope statement count limits
# R1702 - We do not enforce nesting depth limits

[pylama:pycodestyle]
max_line_length = 125

[pylama:pylint]
max_line_length = 125
extension-pkg-whitelist = lxml

[pylama:*/tests/*]
linters = pycodestyle,pyflakes,pylint,eradicate
```

I recommend documenting all linting ignores for future reference.

[Pylint](https://github.com/PyCQA/pylint) needs visibility into your dependencies, so here is my `buildout.coredev` `local.cfg` for reference as well:

```
[buildout]
extends =
    buildout.cfg

parts +=
    pylama

extensions +=

development-packages +=

auto-checkout +=

always-checkout = true

allow-picked-versions = true
show-picked-versions = true

[buildout:python2]
extensions -=
    buildout.dumppickedversions

[branches]

[versions]
astroid =
collective.xmltestreport =
eradicate =
isort =
mccabe =
pycodestyle =
pydocstyle =
pyflakes =
pylama =
pylint =
setuptools =
zc.buildout =
zope.testrunner =

[versions:python2]
plone.recipe.zope2instance = < 5.0.0
pylint = < 2.0.0

[instance]
zserver-threads = 1

eggs +=

environment-vars +=

[pylama]
recipe = zc.recipe.egg:scripts
eggs =
    ${instance:eggs}
    ${test:eggs}
    eradicate
    isort
    pylama
    pylama-pylint
    setuptools
```

This way `bin/pylama` does what it should and my editor integration can be pointed at it.

**Pull request closed without merging**
