### PR TITLE
Make masking specific validation errors configurable 

### PR DESCRIPTION
**Pull request by fredvd**
in DX DeserializFromJson. Refs #1211

### CODE REVIEW

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Review by avoinea — APPROVED** [review]
@fredvd

**Comment by tisto** [comment]
@fredvd ci fails.

**Comment by fredvd** [comment]
@tisto To me this seems to be a  ordering issue in a VHM test, only with python3.6 .  It seems  unrelated and random.

https://github.com/plone/plone.restapi/blob/ae90f0e56e50e81c344fb3d0c84bc6cfc8310cab/src/plone/restapi/tests/test_search.py#L751-L759

Maurits suggests adding a 'sorted' to the output in the test and reference list before comparing.

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@tisto Wait, am I seeing this correctly? The [GHA failure](https://github.com/plone/plone.restapi/runs/3486393585?check_suite_focus=true#step:11:138) is in this file:

    /home/runner/work/plone.restapi/plone.restapi/eggs/plone.restapi-7.3.8-py3.6.egg/plone/restapi/tests/test_search.py

In other words: the checkout is not being used.

**Comment by mauritsvanrees** [comment]
Small PR to fix the test setup:
https://github.com/plone/plone.restapi/pull/1214
This simply moves `plone.restapi =` from `buildout.cfg` to `base.cfg`.

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have rebased on master, improved the logic a bit, and fixed the error in the tests. (I have force pushed and amended for clarity.)

**Comment by mauritsvanrees** [comment]
Please start the tests on Jenkins:

- Log in to [jenkins.plone.org](https://jenkins.plone.org) with your github account.
- Go to the 'Build with parameters' form for all relevant Plone versions. You should see direct links to those versions under the 'Some checks haven’t completed yet' box of the pull request.
- Paste the pull request url in that form and build it.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
