### PR TITLE
Fix typo in the tiles_layout field title name.

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@sneridagh even if it is a small change, a changelog entry is mandatory for core packages.

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jensens Doh, I forgot to commit it! Sorry...

**Pull request merged**
