### PR TITLE
Avoid AttributeError on add-on installation

### LINKED ISSUE #465: Upgrade Step Evolution Error: Version
We have a project called Identidade de Governo (IDG) https://github.com/plonegovbr/brasil.gov.portal whose version was updated from 1.4 to 1.5. 
_plone.restapi_ was incorporated in version 1.5 (https://github.com/plonegovbr/portal.buildout/blob/2e0a598f4e330fd6ebb43d815d5b1e4d7ea82a4c/buildout.d/versions.cfg#L106) which was not present in the previous version, 1.4. 
We have a portal in production with real contents. During the Upgrade Steps from 1.4 to 1.5 in this portal, we ran into this error message:

> Traceback (innermost last):
> Module ZPublisher.Publish, line 138, in publish
> Module ZPublisher.mapply, line 77, in mapply
> Module ZPublisher.Publish, line 48, in call_object
> Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
> Module Products.GenericSetup.upgrade, line 166, in doStep
> Module brasil.gov.portal.upgrades.v10803, line 21, in install_restapi
> Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 602, in installProduct
> __traceback_info__: ('plone.restapi',)
> Module Products.GenericSetup.tool, line 388, in runAllImportStepsFromProfile
> __traceback_info__: profile-plone.restapi:default
> Module Products.GenericSetup.tool, line 1433, in _runImportStepsFromContext
> Module Products.GenericSetup.tool, line 1245, in _doRunImportStep
> __traceback_info__: plone.restapi
> Module plone.restapi.setuphandlers, line 32, in import_various
> Module plone.restapi.setuphandlers, line 12, in install_pas_plugin
> AttributeError: __contains__
relatorio de upgrade steps do portal federativo-1_html_6d69e603

### PR DESCRIPTION
**Pull request by hvelarde**
fixes #465

### CODE REVIEW

**Comment by hvelarde** [comment]
seems we have found another bug here:

```pypdb
(Pdb) l
 92  	                         res['error']['message'])
 93  	        self.assertNotIn('token', res)
 94  	
 95  	    def test_login_with_zope_user(self):
 96  	        self.layer['app'].acl_users.plugins.users.addUser(
 97  	            'zopeuser', 'zopeuser', 'secret')
 98  	        self.request['BODY'] = '{"login": "zopeuser", "password": "secret"}'
 99  	        service = self.traverse()
100  	        res = service.reply()
101  	        import pdb; pdb.set_trace()
102  ->	        self.assertEqual(200, self.request.response.getStatus())
(Pdb) res
{'error': {'message': 'JWT authentication plugin not installed.', 'type': 'Login failed'}}
(Pdb) uf = getToolByName(self.portal, 'acl_users')
(Pdb) uf
<PluggableAuthService at /plone/acl_users>
(Pdb) 'jwt_auth' in uf
True
```

**Comment by hvelarde** [comment]
awesome! the pull request is now ready.

**Comment by lukasgraf** [comment]
Thanks! 🎉 Glad we were finally able to track this one down 😃

**Comment by sunew** [comment]
great work! 😊

**Comment by hvelarde** [comment]
@tisto can we have a new release?

**Comment by tisto** [comment]
@hvelarde https://pypi.org/project/plone.restapi/3.4.5/#id1

**Comment by hvelarde** [comment]
@lukasgraf I think we forgot to add a `docstring` to `install_pas_plugin()` to explain the purpose of that piece of code; it was not obvious to me that is was installing the authentication plugin in Zope's root.

**Pull request merged**
