### PR TITLE
Testfix for changes in `zope.schema >= 7.0.0`

### LINKED ISSUE #1567: `zope.schema >= 7.0.0` changed type of `schema.Int`
Just figured out, that `zope.schema.Int` Field changed it's validation basis `_type` from `(int, )` to `int` since version `7.0.0` (they dropped the `zope.schema._compat.py` module). Some tests here check the `WrongType` exception on validation and have to be updated accordingly.

### PR DESCRIPTION
**Pull request by petschki**
fixes #1567

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
Hm ... I think this needs review of @plone/release-team ... is it planned to ship Plone 6.0.x with Zope 5.8 ? And does it make sense to test Plone 5.2 on master branch? `buildout.coredev#5.2` has `branch=7.x.x` in its sources.cfg for plone.restapi ...

**Comment by mauritsvanrees** [comment]
Yes, Plone 6.0.1 will ship with Zope 5.8. There is no 5.7.x maintenance branch, so there really is no other option than following along.
As a temporary workaround we could pin an older zope.schema in coredev 6.0.

And yes, plone.restapi is one of a few packages that we (so far) are trying to keep running on both Plone 5.2 and 6.0, although only on Python 3. On 5.2 it is an optional upgrade for those that want it.

**Comment by petschki** [comment]
OK, I think I can change this testfix to work for both zope.schema versions in that case.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Pull request merged**
