### PR TITLE
Use correct subclass for SubjectsFieldJsonSchemaProvider, fixes #710

### LINKED ISSUE #710: type for subject field is wrong
The type for the subject field is currently `string`, but the data is a list.

Data endpoint:
```
  "subjects": [
    "Plone",
    "Überplone",
    "Volto"
  ],
```

@types end point:
```
    "subjects": {
      "choices": [
        [
          "Plone",
          "Plone"
        ],
        [
          "Volto",
          "Volto"
        ],
        [
          "=C3=9Cberplone",
          "Überplone"
        ]
      ],
      "description": "Tags are commonly used for ad-hoc organization of content.",
      "enum": [
        "Plone",
        "Volto",
        "=C3=9Cberplone"
      ],
      "enumNames": [
        "Plone",
        "Volto",
        "Überplone"
      ],
      "title": "Tags",
      "type": "string",
      "vocabulary": "plone.app.vocabularies.Keywords"
    },
```

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by MrTango** [comment]
@jaroel we should also add tests for this and for the related items provider, but i have no idea how to test the named adapter there.

**Comment by tisto** [comment]
FYI: This is a breaking change, which would require writing an upgrade guide section.

**Comment by tisto** [comment]
@MrTango @jaroel we completely refactored the way we handle the subjects field over the last p.restapi releases. I still don't fully understand what this is about. Though, I think this PR is outdated. Do you agree?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
