### PR TITLE
backport #1465: @site and @navroot endpoints

### PR DESCRIPTION
**Pull request by erral**
Backport of #1465 to 7.x.x to have it for https://github.com/plone/volto/pull/5185

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
See: https://github.com/plone/volto/pull/5185

**Comment by erral** [comment]
eh... how are we testing the 7.x.x branch in python 2.7? It is not available on github actions... @plone/restapi-team

**Comment by erral** [comment]
> @erral There is still a Jenkins job which tests on Python 2.7

where all robot tests fail 😒

**Comment by davisagli** [comment]
@erral There are some syntax errors in Python 2

**Comment by davisagli** [comment]
@erral I think it would be fine to disable the new endpoints entirely for Plone 4.3 (i.e. with conditional zcml, plus skipping the tests on 4.3)

**Comment by davisagli** [comment]
@erral Oops, right, I forgot. Carry on, then.

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
Green!

**Review by davisagli — APPROVED** [review]
@erral Thanks!

**Comment by mauritsvanrees** [comment]
I have released this in `plone.restapi` 7.9.0.

**Pull request merged**
