### PR TITLE
Control Panels Plone 4 support

### PR DESCRIPTION
**Pull request by avoinea**
Enable Plone 4 compatible endpoints:
* Add-ons
* Dexterity Content Types

### CODE REVIEW

**Comment by tisto** [comment]
@avoinea just out of curiosity: are you using Volto with Plone 4?

**Comment by tisto** [comment]
@avoinea I am ok with enabling those control panels for Plone 4 if you have the use case. Travis is currently red thg.

**Comment by avoinea** [comment]
```
61 files would be reformatted, 185 files would be left unchanged.
The command "if [ "$PLONE_VERSION" == "5.2.x" ] && [ $TRAVIS_PYTHON_VERSION == '3.7' ]; then pip install black && black src/ --check; fi" exited with 1
```
I don't think I changed so many files with this PR :smile:

**Comment by tisto** [comment]
@avoinea ok, this is a know issue. We do not pin black and the new recently released version just reformats more things. Will fix this in master, then you can rebase.

**Comment by tisto** [comment]
@mauritsvanrees @esteele do we currently pin black in any released Plone version? The black versions differ in their output and it would be good IMHO if we would pin them in the core so not every single project has to do this (at least not in the long run).

**Comment by avoinea** [comment]
> @avoinea just out of curiosity: are you using Volto with Plone 4?

:smile:  I know. But as crazy as it may look like, it just works :tada:

**Comment by mauritsvanrees** [comment]
@tisto No, I don't see pins for black anywhere in coredev. I also don't see it in `buildout.plonetest` or `bobtemplates.plone`.  I see two clients where we pin it: `black = 19.10b0`.

I think a pin in core would be fine. Downside is that this probably gives us several extra version pins for dependencies (although some are already pinned anyway).  In a fresh venv:

```
$ bin/pip freeze
appdirs==1.4.4
black==20.8b1
click==7.1.2
mypy-extensions==0.4.3
pathspec==0.8.0
regex==2020.7.14
toml==0.10.1
typed-ast==1.4.1
typing-extensions==3.7.4.3
```

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@tisto Looks like all the tests are passing for this one.

**Review by tiberiuichim — APPROVED** [review]

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@tisto Did this merge hit any release, yet?

**Comment by tisto** [comment]
@avoinea not yet. I merged it into the 6.x.x branch but I had to revert. Will go into the next 7.x alpha release...

**Pull request merged**
