### PR TITLE
Pass through field attribute 'widget' for all fields (was "Pass through field attribute 'widget' for field Dict")

### PR DESCRIPTION
**Pull request by ksuess**
As the Dict field is a mighty field that can be used for many diverse dictionaries and diverse use cases, we need the widget info to let Volto know which widget to apply.

### CODE REVIEW

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by tiberiuichim** [comment]
I think we can generalize this case and pass the widget for all fields, does it make sense?

**Review by sneridagh — APPROVED** [review]

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Review by tiberiuichim — APPROVED** [review]

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Comment by ksuess** [comment]
@tisto, would you merge this, thanks.

**Comment by tisto** [comment]
@ksuess merged. Do you want me to do a release or wait for https://github.com/plone/plone.restapi/pull/1160?

**Comment by ksuess** [comment]
> @ksuess merged. Do you want me to do a release or wait for #1160?

thanks for asking.
https://github.com/plone/plone.restapi/pull/1163 is ready for reviewing (supersedes #1160)

**Pull request merged**
