### PR TITLE
Serializer, Check read permission

### LINKED ISSUE #56: Check field permissions for GET request
Currently the script doesn't check if the user is permitted to view the fields on a page (custom permission). Is something like this implemented or on the todo list already?

### PR DESCRIPTION
**Pull request by casdr**
Closes #56 in favor of PR 61

### CODE REVIEW

**Comment by buchi** [comment]
:+1:

**Comment by tisto** [comment]
Thanks @casdr! Would you mind adding a changelog entry in CHANGES.rst with your name?

**Comment by buchi** [comment]
@tisto There's no release yet, so a changelog entry doesn't make sense, right?

**Comment by tisto** [comment]
@buchi right. got confused with plone.rest.

**Pull request merged**
