### PR TITLE
move translations into plone.app.locales

### LINKED ISSUE #841: Move translations to plone.app.locales
Probably because of historical reasons the translations are part of this package. This need to be moved to `plone.app.locales`. I fear we missed that part in past as we added this package to Plone core.

### PR DESCRIPTION
**Pull request by erral**
Fixes #841 

Merge together: 
- https://github.com/collective/plone.app.locales/pull/332
- https://github.com/plone/buildout.coredev/pull/743

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@erral yeah. Sorry, my fault! I did not think about the implications of this move. We can create a milestone Plone6-only and merge this PR when it is ready.

**Comment by jensens** [comment]
This one is completly outdated, since there are only a few locales left in plone.restapi. close?

**Comment by mauritsvanrees** [comment]
This PR was cancelled.  Should we close the related PRs as well then?

- https://github.com/collective/plone.app.locales/pull/332
- https://github.com/plone/buildout.coredev/pull/743

**Comment by tisto** [comment]
@mauritsvanrees I'd say so, yes.

**Pull request closed without merging**
