### PR TITLE
Returns an error message when an Invalid occurs when validating a controlpanel field

### PR DESCRIPTION
**Pull request by wesleybl**
Also translates the message.

Ref: https://github.com/plone/volto/issues/5274

### CODE REVIEW

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@wesleybl Could you add a screenshot of how the error looks now, or give me steps to reproduce it? I can probably figure it out but I'm skimming through a bunch of issues this evening, and it's easier to click "accept" quickly if I can clearly see what the result of the change is.

**Comment by wesleybl** [comment]
@davisagli the steps to reproduce this on the Volto are described in: https://github.com/plone/volto/issues/5274

But this PR here does not make validation errors appear in Volto. It only leaves the compatible restapi response to be displayed in Volto. I'm preparing a PR on Volto to display the errors. But this PR here doesn't "break the screen" if my Volto PR isn't ready. So it's safe to merge first.

With this PR the response with validation error looks like this:

```json
{
  "message": "[{'message': 'Twitter username should not include the \"@\" prefix character.', 'field': 'twitter_username', 'error': 'ValidationError'}]",
  "traceback": [
    "File \"/home/user/.buildout/eggs/cp311/Zope-5.8.5-py3.11.egg/ZPublisher/WSGIPublisher.py\", line 181, in transaction_pubevents",
    "    yield",
    "",
    "  File \"/home/user/.buildout/eggs/cp311/Zope-5.8.5-py3.11.egg/ZPublisher/WSGIPublisher.py\", line 391, in publish_module",
    "    response = _publish(request, new_mod_info)",
    "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/.buildout/eggs/cp311/Zope-5.8.5-py3.11.egg/ZPublisher/WSGIPublisher.py\", line 285, in publish",
    "    result = mapply(obj,",
    "             ^^^^^^^^^^^",
    "",
    "  File \"/home/user/.buildout/eggs/cp311/Zope-5.8.5-py3.11.egg/ZPublisher/mapply.py\", line 98, in mapply",
    "    return debug(object, args, context)",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/.buildout/eggs/cp311/Zope-5.8.5-py3.11.egg/ZPublisher/WSGIPublisher.py\", line 68, in call_object",
    "    return obj(*args)",
    "           ^^^^^^^^^^",
    "",
    "  File \"/home/user/.buildout/eggs/cp311/plone.rest-3.0.1-py3.11.egg/plone/rest/service.py\", line 22, in __call__",
    "    return self.render()",
    "           ^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/git/plone.restapi/src/plone/restapi/services/__init__.py\", line 19, in render",
    "    content = self.reply()",
    "              ^^^^^^^^^^^^",
    "",
    "  File \"/home/user/git/plone.restapi/src/plone/restapi/services/controlpanels/update.py\", line 41, in reply",
    "    deserializer()  # The deserializer knows where to put it.",
    "    ^^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/git/plone.restapi/src/plone/restapi/deserializer/controlpanels/__init__.py\", line 89, in __call__",
    "    raise BadRequest(errors)"
  ],
  "type": "BadRequest"
}
```

**Comment by wesleybl** [comment]
@davisagli I make the Volto PR: https://github.com/plone/volto/pull/5950

**Review by nileshgulia1 — COMMENTED** [review]
Tested and works fine with https://github.com/plone/volto/pull/5950

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@tisto @davisagli @sneridagh can you take a look here please?

**Review by davisagli — APPROVED** [review]
Tested in combination with https://github.com/plone/volto/pull/5950, looks good. thanks @wesleybl!

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
