### PR TITLE
Point to the correct repository branch for sphinx-book-theme

### PR DESCRIPTION
**Pull request by stevepiercy**
Fix the link in the GitHub menu item "suggest edit" to point to master branch.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Does anyone know why the tests for 6.0 fail? This change should not affect app tests.

**Comment by stevepiercy** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
Can someone tell me how to rerun a single failed test on Jenkins, specifically [Plone Jenkins CI - pull-request-6.0-3.9](https://jenkins.plone.org/job/pull-request-6.0-3.9/1051/)?

**Comment by stevepiercy** [comment]
Weird. The same tests passed on https://github.com/plone/plone.restapi/pull/1351

**Comment by mauritsvanrees** [comment]
> Can someone tell me how to rerun a single failed test on Jenkins, specifically [Plone Jenkins CI - pull-request-6.0-3.9](https://jenkins.plone.org/job/pull-request-6.0-3.9/1051/)?

- Go to jenkins.plone.org
- Click on Log in. That should work with your GitHub account.
- Go to the PR job and click on "Build with parameters": https://jenkins.plone.org/job/pull-request-6.0-3.9/build?delay=0sec
- Copy-paste the url of the current PR in the form and click Build.

In this case the failure is that the Chrome browser cannot be found during one of the robot tests. A failure that unfortunately sometimes happens. But really this PR changes nothing that has any effect on Jenkins, so I will approve and merge.

**Review by mauritsvanrees — APPROVED** [review]

**Comment by stevepiercy** [comment]
Got it. I walked through the steps, except clicking "Build" to save build time.

Thank you for the approval.

**Pull request merged**
