### PR TITLE
Blocks transformers also on root

### PR DESCRIPTION
**Pull request by cekk**

### CODE REVIEW

**Comment by cekk** [comment]
see #1043

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Review by tiberiuichim — APPROVED** [review]

**Review by tisto — CHANGES_REQUESTED** [review]
CI is failing for 5.1 and 4.3

**Comment by cekk** [comment]
I know, there is an error on buildout getting PyJWT.
It seems a problem with setuptools and python2

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]
LGTM

**Review by tisto — APPROVED** [review]

**Pull request merged**
