### PR TITLE
Use _getsafeMemberId when checking for user portrait

### PR DESCRIPTION
**Pull request by instification**
This is a very minor PR.

Currently when checking for user portrait it checks to see if the user is in `memberdata.portraits` however it is not sanitising the user id, meaning some users don't get their portrait returned even if it exists. For example if there is a hyphen in the user id.

### CODE REVIEW

**Comment by instification** [comment]
@jenkins-plone-org please run jobs

**Comment by instification** [comment]
the 2 failing tests seem to be unrelated and are failing on other pr's/jobs. I'm not sure what to do in this scenario

**Review by jensens — APPROVED** [review]

**Review by ksuess — APPROVED** [review]

**Comment by instification** [comment]
@jenkins-plone-org please run jobs

**Comment by instification** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
