### PR TITLE
Reorganize navigation

### LINKED ISSUE #1486: Reorganize navigation items in docs
The docs are rendered as a huge flat list, with not enough thought for organization. I propose to organize and sort them as follows.

- Put endpoint docs into new directory `endpoints/`.
- Put usage docs into new directory `usage/`. These include items that span the endpoints.
- Create a new `contributing` directory for how to contribute.

```
introduction  # has toctrees for content-negotiation and plone-content

usage/
    authentication
    batching
    content
    customization
    exploring
    i18n
    serialization
    sharing
    types-schema
    blocks

endpoints/
    actions
    addons
    breadcrumbs
    comments
    contextnavigation
    controlpanels
    copymove
    database
    email-notification
    email-send
    expansion
    groups
    history
    locking
    navigation
    portrait
    principals
    querystring
    querystringsearch
    registry
    roles
    searching
    system
    tiles
    translations
    tusupload
    types
    users
    vocabularies
    workflow
    workingcopy

upgrade-guide

contributing -> contributing/index
contributing/
    index
    conventions
```

Please let me know what y'all think. Thank you!

### PR DESCRIPTION
**Pull request by stevepiercy**
Fixes #1486

### CODE REVIEW

**Comment by stevepiercy** [comment]
Here are some screenshots of the reorganized navigation and how it will appear in the main documentation.

## Home page navigation

Screen Shot 2022-09-13 at 3 38 29 AM

## REST API index

Screen Shot 2022-09-13 at 3 39 36 AM

## Usage index

Screen Shot 2022-09-13 at 3 39 52 AM

## Endpoints index

Screen Shot 2022-09-13 at 3 40 16 AM

## Contributing to `plone.restapi` index

Screen Shot 2022-09-13 at 3 40 39 AM

**Comment by stevepiercy** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
I don't know why that one test fails. I committed all the changes, and I did not change the file it complains about. Anyone got an idea of how to fix it?

**Review by jensens — APPROVED** [review]
I also have no idea about the test failure (is it unrelated?). Anyway, if resolved this one is ready.

**Comment by davisagli** [comment]
Hopefully https://github.com/plone/plone.restapi/commit/94f803d3c57db9ead809ac6d7eb3c92f9cfa2be8 will take care of that test...

**Comment by davisagli** [comment]
@stevepiercy LGTM in the screenshots. Could you take care of resolving the conflict? I glanced at it but don't have enough context to be sure I'm doing it correctly. After that the test should pass.

**Comment by stevepiercy** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
3/4 Jenkins pass, 1 still fails:

```
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 105.0.5195.102 with binary path /usr/bin/google-chrome
```

I restarted that one failing run again. Third time is a charm?

GitHub still shows all 4 runs as pending, when 3 should show as passed.

**Comment by stevepiercy** [comment]
All Jenkins runs pass now.

GitHub still shows them as pending.

Merging now.

**Comment by davisagli** [comment]
@stevepiercy Reporting of the jenkins PR job status back to github is currently broken. I submitted a fix in https://github.com/plone/jenkins.plone.org/pull/306

**Pull request merged**
