### PR TITLE
Add docs onboarding postman usage

### PR DESCRIPTION
**Pull request by acsr**
The Postman onboarding by Lukas Graf of OneGov was reviewed & translated. Thanks for the base work!

* Markup was heavily improved  to take advantage of latest Sphinx directives. 
* Glossary terms were added to specifically invite HTTP newbies to enter REST API exploration. * * ToDo: Some Glossary entries need more love but I can live with them for now. 

**Improved styling of the Docs**

This update adds some snippets to the _templates folder and a custom.css and the toggle class for admonitions to allow additional information being hidden first (as discussed with Timo during the Sprint). All these styling parts are more or less stolen from the Plone.Training theme. 

**ToDo & Warning!** 

After rebuilding the docs using the bare "make html" lots of these changes are not taken in an existing HTML build with the simple update. You have to manually delete the local "html" folder of a former build and reissue "make html" again . 

**Due to a current bug in the Sphinx setup of plone.restapi** the usual and official "clean" part of a  "make clean html" will **wipe out currently your local files including the source files** (see Makefile line 43).  You can restore the content using a "git checkout docs"

This needs to be reconfigured as a next step.

### CODE REVIEW

**Comment by tisto** [comment]
@acsr thanks for your contribution! That's awesome! Though, I wasn't able to build the docs on this branch. Will have another look today. Could you create a separate ticket for the sphinxbuilder issue please?

**Comment by tisto** [comment]
@acsr I gave it a second try and now it works! I also checked the document. Looks good. Though, I was wondering if a more narrative writing style would be a better fit for newbies (which we address with this howto).

**Comment by acsr** [comment]
@tisto I was following mostly the "story narration" in the source of @lukasgraf but at some points switched to a more step by step approach. If you cast the actual steps by spicing them up with filling in "natural" language that is usefull for spoken text in a screencast. But just if you start to display rendered text on screen, reading time takes seriously longer because you have not the emphasize of a speaker – and, that is the main issue – decoding and rendering back from prose to the actual steps is much more time consuming and difficult to imagine. 

"Newbie reading" without existing context is very different to your understanding as the author or an insider with background. 

My POV: Too narrative docs are boring.

Instead of splitting the sentences into actual steps, the bulletpoints already deliver the structure.

If you see particular parts of the content by Lukas to be enhanced, let me now by blaming the lines.

I usually switch to "reader mode" after writing and currently see no pain issues that are blockers. The "clean" issue is a new ticket, and was only mentioned to prevent a blocker during the review of this pull request. 

Please merge first and we can improve later, because we avoid an upcoming merge risk during evolving of the content.

**Comment by tisto** [comment]
@acsr sure. merge now and improve later is fine with me. Thanks for your contribution!

**Pull request merged**
