### PR TITLE
Cleanup/Update pas plugin

### PR DESCRIPTION
**Pull request by jensens**
- security decorators
- increase readability/simplify code
- remove six in pas module
- update ZMI-zpt to match Zope4/BS4
- f-strings
- remove return None madness ;)
- do not require a coding magic line, UTF-8 is default in Python 3, so it does not need to be declared.

### CODE REVIEW

**Comment by tisto** [comment]
@jensens thanks for working on this! I personally prefer to split stuff into smaller PRs (e.g. coding magic / return None) that we can quickly review and merge. This allows us to merge your work sooner. :)

**Comment by jensens** [comment]
I can split it up.

**Comment by jensens** [comment]
First lets merge #1155 #1156 and #1157 then I'll go on with this one.

**Comment by jensens** [comment]
see also #1158

**Comment by jensens** [comment]
start over

**Pull request closed without merging**
