### PR TITLE
handle sort_on and sort_order parameters to allow both lists and strings

### LINKED ISSUE #1532: @search endpoint does not handle correctly multiple values for `sort_on` and `sort_order` parameters
ZCatalog allows to sort items according to several indexes. To do so, one needs to pass a list of indexes in the `sort_on` parameters and a list of critaria to the `sort_order` parameter.

When doing so using the `@search` endpoint, the `ZCatalogCompatibleQueryAdapter` converts those lists to strings, converting `['effective', 'sortable_title']` to `"['effective', 'sortable_title']"` and definitely invalidating any sorting attempt.

### PR DESCRIPTION
**Pull request by erral**
Fixes #1532 

Tests are missing... I can't find any test for the `ZCatalogCompatibleQueryAdapter`... I will try to write something.

### CODE REVIEW

**Comment by jensens** [comment]
Phew, type casting on stereoids ;-)

**Comment by tisto** [comment]
CI failures. Some are known issues we have to tackle that are unrelated to this PR.

**Comment by jensens** [comment]
implementation LGTM, docs and changelog are missing.

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
I  have added some documentation

**Review by jensens — APPROVED** [review]

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]
LGTM!

**Pull request merged**
