### PR TITLE
Update expected Basic Auth in documentation.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
It is longer now, for some reason. Does anyone know why? Or will this change randomly?

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Still some [differences](https://github.com/plone/plone.restapi/actions/runs/3496320898/jobs/5854095701).

A few date time / time zone issues like this:

```
diff --git a/src/plone/restapi/tests/http-examples/comments_get.resp b/src/plone/restapi/tests/http-examples/comments_get.resp
index ce8d86a..29b41b4 100644
--- a/src/plone/restapi/tests/http-examples/comments_get.resp
+++ b/src/plone/restapi/tests/http-examples/comments_get.resp
@@ -13,11 +13,11 @@ Content-Type: application/json
             "author_username": null,
             "can_reply": true,
             "comment_id": "1400000000000000",
-            "creation_date": "1995-07-31T13:45:00+00:00",
+            "creation_date": "1995-07-31T13:45:00",
             "in_reply_to": null,
             "is_deletable": true,
             "is_editable": true,
-            "modification_date": "1995-07-31T17:30:00+00:00",
+            "modification_date": "1995-07-31T17:30:00",
             "text": {
                 "data": "Comment 1",
                 "mime-type": "text/plain"
```

Nice password, might be fixed after Plone 6 rc1 is out and we use it in the tests:

```
--- a/src/plone/restapi/tests/http-examples/jwt_login.req
+++ b/src/plone/restapi/tests/http-examples/jwt_login.req
@@ -4,5 +4,5 @@ Content-Type: application/json
 
 {
     "login": "admin",
-    "password": "secret"
+    "password": "correct horse battery staple"
 }
```

Three star token which differs from... a three star token?:

```
-- a/src/plone/restapi/tests/http-examples/jwt_login.resp
+++ b/src/plone/restapi/tests/http-examples/jwt_login.resp
@@ -2,5 +2,5 @@ HTTP/1.1 200 OK
 Content-Type: application/json
 
 {
-    "token": "***"
+    "token": "***"
 }
```

Another possible timezone problem, with a time difference of exactly two hours, although it *could* be a real error in what restapi returns:

```
--- a/src/plone/restapi/tests/http-examples/workingcopy_baseline_get.resp
+++ b/src/plone/restapi/tests/http-examples/workingcopy_baseline_get.resp
@@ -50,7 +50,7 @@ Content-Type: application/json
         "locked": true,
         "name": "iterate.lock",
         "stealable": false,
-        "time": 807204600.0,
+        "time": 807211800.0,
         "timeout": 4294967280,
         "token": "0.12345678901234567-0.98765432109876543-00105A989226:1630609830.249"
     },
```

**Comment by davisagli** [comment]
@mauritsvanrees The change in the Basic Auth is because I changed the test user password to `correct horse battery staple` in 6.0b3 to meet the new length requirement of 8 characters. But then I realized that requires updating lots of tests like these, so I changed it back to the old value. (https://github.com/plone/plone.app.testing/pull/79) So: I think once plone.restapi's buildout is updated to use Plone 6.0rc1, this update will no longer be needed.

The first date/time difference looks related to https://github.com/plone/plone.restapi/pull/1531. Hmm, why did the builds not fail on that PR?

**Comment by tisto** [comment]
@mauritsvanrees @davisagli FYI: I create a new PR upgrading buildout to rc1: 

https://github.com/plone/plone.restapi/pull/1541

**Comment by mauritsvanrees** [comment]
Closing this one in favour of a few others.

**Pull request closed without merging**
