### PR TITLE
Validate the id in the content POST service

### LINKED ISSUE #1487: It's possible to set an invalid short name when adding content
If an `id` is specified while creating content via the [FolderPost](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/content/add.py) endpoint, it is used without validating that it meets the criteria for a valid id. For example, it's possible to add an item with an id containing spaces.

What I would expect: either the id should be normalized (this is what already happens if it is set while editing the item later), or trying to add an item with an invalid id should return a 400 response with a helpful error message.

Note: This might be considered a backwards incompatible change, since someone calling the API may be assuming that the item has the id that was specified, and not a normalized form of it. But, it could also be considered a bugfix, because it never should have been possible to add items with an invalid id.

Thoughts on how to handle this, @tisto?

### PR DESCRIPTION
**Pull request by davisagli**
Fixes #1487

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
can you also add tests for special IDs?

For instance if you try to add a content titled 'layout' the created item is 'layout-1' or if you try to manually set an id with an space, the space is exchanged with a - in classic ui.

See https://6-classic.demo.plone.org/en/demo/layout-1

https://6-classic.demo.plone.org/en/demo/i-ill-try-to-add-a-whitespace-in-the-id-1

Or when adding a page titled 'subjects' it fails https://6-classic.demo.plone.org/en/demo/subjects/view

**Comment by davisagli** [comment]
@erral Sure. This should take care of that too, but I'll add a test

**Comment by davisagli** [comment]
@erral There was already a test for converting spaces to dashes when I first submitted the PR.

I added a test for layout --> layout-1 in https://github.com/plone/plone.restapi/pull/1488/commits/cce52eb33ea81508d95205f1a476dd80a3f118a4

The case with `subjects` is different; I think that needs to be fixed somewhere else since the classic UI is also allowing it. Possible in https://github.com/plone/plone.base/blob/main/src/plone/base/utils.py#L351

**Review by mauritsvanrees — COMMENTED** [review]
Should be okay, but I have just voiced a doubt in the [issue](https://github.com/plone/plone.restapi/issues/1487#issuecomment-1242551621).

**Review by jensens — APPROVED** [review]

**Comment by davisagli** [comment]
Based on the discussion in #1487, I decided that it's better to return an error response instead of normalizing the id, since the client explicitly requested a specific id and may not want to get something different.

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

(seems the Github reporting of Jenkins is failing, all jobs pass except the last one)

**Pull request merged**
