### PR TITLE
Fix for #1628

### PR DESCRIPTION
**Pull request by 1letter**
- unset the GET Paramter in Service QuerystringSearchGet
- rename test_querystringsearch_metadata_fields to test_querystringsearch_metadata_fields_post
- add test_querystringsearch_metadata_fields_get

### CODE REVIEW

**Comment by tisto** [comment]
@davisagli @robgietema could you have a look at this PR tomorrow?

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]
@1letter Thanks for the fix and test! And sorry for the delay in reviewing.

**Pull request merged**
