### PR TITLE
Add Matomo Analytics, Remove Google Analytics

### PR DESCRIPTION
**Pull request by stevepiercy**
Fixes https://github.com/plone/plone.restapi/issues/1447

### CODE REVIEW

**Comment by stevepiercy** [comment]
Is it OK to skip running Jenkins for this PR? It's only minor changes to the docs template and configuration.

**Review by fredvd — APPROVED** [review]

**Review by fredvd — APPROVED** [review]
Lgtm.  It’s only the docs template and all tests pass.  @ksuess I assume we don’t  need another check from a plone.restapi ‘code’ developer?

**Comment by stevepiercy** [comment]
I requested reviews from a few other plone.restapi contributors, including @sneridagh, @tisto, @erral, @mauritsvanrees

**Review by erral — APPROVED** [review]
I am OK with this. If Foundation's policy is to replace Google with Matomo ir is OK

**Comment by stevepiercy** [comment]
Yes. Google Analytics is not GDPR compliant, and Matomo is.

**Pull request merged**
