### PR TITLE
Resolve paths to UIDs

### LINKED ISSUE #808: Resolve UID for blocks
plone.restapi currently does not serialize/deserialize links to UIDs in tiles. We would need to:

1) Serialize links/paths to UIDs when doing a POST request via the REST API
2) Deserialize UIDs to links/paths when doing a GET request via the REST API

We should be able to re-use the existing portal transforms for this. Though, we need to write a JSON-parser that parses the "tiles" attribute of a content object and replaces links/UIDs in the parts of the JSON where this makes sense.

### PR DESCRIPTION
**Pull request by buchi**
On deserialization resolve paths UIDs.
On serialization resolve UIDs to paths.

Closes #808

### CODE REVIEW

**Comment by buchi** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
whats the state here? there are no labels set!

**Comment by tisto** [comment]
@jensens we need to properly test it and make sure we covered all the edge cases. Then somebody needs to test this in pre-production. Then we can merge and release.

**Comment by tisto** [comment]
Note: resolveuid seems to fail on the Volto front-page.

**Pull request merged**
