### PR TITLE
The `@controlpanels/usergroup` does not work for Plone 5 since it doe…

### PR DESCRIPTION
**Pull request by sneridagh**
…s not exist there. Bring back the missing `title` just for Plone 5.

@ksuess sorry, my bad for removing the title, I didn't know that it was a P6 only control panel.

### CODE REVIEW

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
Sorry, Plone 5 is not my habitat. Maybe @erral can check?

**Review by tisto — APPROVED** [review]

**Comment by erral** [comment]
So this is the reason of our error last week!

We fixed it adding the controlpanel to the controlpanel.xml file and importing the profile because we thought we were missing some import step...

**Comment by sneridagh** [comment]
Sorry about that, I'm the one to blame because I removed the title and group because it worked in 6... but obviously not in 5. And since Volto was using an old p.restapi version I didn't realised...

**Pull request merged**
