### PR TITLE
Show expired content when GET on a folderish object, include a way to…

### PR DESCRIPTION
**Pull request by sneridagh**
… display it on @search via the show_inactive parameter

### CODE REVIEW

**Comment by sneridagh** [comment]
Related to #388

**Comment by sneridagh** [comment]
@ebrehault didn't tackled yet the exclude_from_nav since it will require more thought and the addition of the index...

**Comment by buchi** [comment]
This exposes more information than the default Plone interface.
Plone's search view never shows inactive items for users without "Access inactive portal content". See: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py#L126
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L458

Also `folder_listing` doesn't show inactive content without "Access inactive portal content" permission.

We should already have the default behavior, meaning if you have "Access inactive portal content" permission you will automatically get expired content in @search and items listing.

@sneridagh @ebrehault What's your use case for this? Doesn't the default behavior work out for you?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
