### PR TITLE
Add `include_items` option to `SerializeFolderToJson`.

### PR DESCRIPTION
**Pull request by Gagaro**
This allow to get only the content without its children. It avoids a catalog query when not needed.

I didn't find test for testing the content GET, did I miss them?

### CODE REVIEW

**Comment by tdesvenain** [comment]
This would be nice if we could pass a value like '0' / '1' or 'True' / 'False' @tisto what is the more standard way to do this in plone.restapi ?

**Comment by tisto** [comment]
@Gagaro thanks for your contribution. Could you have a look at https://github.com/plone/plone.restapi/pull/442 please and let us know if that maybe solves your issue?

**Comment by Gagaro** [comment]
No it only remove items for fullobject from catalog. My idea was to be able to get a container object without its items.

I'll have to rework this PR.

#442 does not include the new feature for AT, is this on purpose?

**Comment by Gagaro** [comment]
I rebased the PR on master.

**Comment by tisto** [comment]
@tdesvenain @Gagaro we had a discussion about boolean URL parameter best practices here:

https://github.com/plone/plone.restapi/pull/436

Recommended options:

?fullobjects=false
?fullobjects=true

Other options:

?fullobjects -> True (for backwards compatibility)
?fullobjects=1 -> True
?fullobjects=0 -> False
?fullobjects=True -> True
?fullobjects=true -> True
?fullobjects=False -> False
?fullobjects=false -> False
?fullobjects=<ANYTHING ELSE> -> needs to be decided

**Comment by Gagaro** [comment]
I added a `boolean_value` method to handle the GET parameter. It will be `False` for a value equal to False, 'false', 'False', '0' or 0 and `True` for everything else.

What do you think about that?

**Comment by tisto** [comment]
@sneridagh any chance you can have a look at this pull request?

**Comment by sneridagh** [comment]
@Gagaro You are right, #442 didn't include support for AT. I would add it in this PR as well (since it's related at the end). I would also add further tests for the GET including the `include_items` querystring. What do you think, could you please take care of it? Thx!

**Comment by Gagaro** [comment]
I updated the PR.

**Comment by sneridagh** [comment]
@Gagaro It seems there are some PEP8 issues:

```
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:0:1: C101 Coding magic comment not found
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:13:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:16:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:19:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:22:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:25:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:28:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:31:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:34:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_boolean_value.py:37:1: W293 blank line contains whitespace
/home/travis/build/plone/plone.restapi/src/plone/restapi/serializer/atcontent.py:97:80: E501 line too long (92 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/serializer/atcontent.py:113:80: E501 line too long (81 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/serializer/dxcontent.py:129:80: E501 line too long (92 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/__init__.py:22:80: E501 line too long (89 > 79 characters)
/home/travis/build/plone/plone.restapi/src/plone/restapi/deserializer/__init__.py:27:12: E713 test for membership should be 'not in'
```

**Comment by Gagaro** [comment]
Sorry about that, it's fixed.

**Comment by tisto** [comment]
@Gagaro thanks for your quick reaction and fix! Just wondering, didn't you get a notification by the pre-commit hook about the pep8 violations?

**Comment by Gagaro** [comment]
No, `code-analysis` does not show anything but `flake8` itself does (and I just catched one more with `flake8`):

```
» ./bin/code-analysis
Flake8...............................[ OK ] in 1.265s
 » flake8 src
src/plone/restapi/testing.py:89:1: E305 expected 2 blank lines after class or function definition, found 1
src/plone/restapi/deserializer/__init__.py:28:12: E713 test for membership should be 'not in'
```

**Comment by tisto** [comment]
@Gagaro crap. We encountered similar issues in our project. No idea what's wrong with pep8/flake8/p.r.codeanalysis lately. I somehow suspect different pep8/flake8 versions could cause the problem.

**Comment by tisto** [comment]
@Gagaro merged. Thanks for your contribution! You should add yourself to the list of contributors btw. :)

**Comment by Gagaro** [comment]
Just did, thanks

**Pull request merged**
