### PR TITLE
Fix tests for https://github.com/plone/Products.CMFPlone/issues/3486

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by tisto** [comment]
@pbauer can you elaborate on this? I guess we might need an if/else here for different Plone versions? Keep in mind that plone.restapi needs to support Plone 5.2 and Plone 6 at the same time.

**Comment by pbauer** [comment]
I'll add if/else clases. After https://github.com/plone/plone.restapi/pull/1364 is merged we can check here for Plone 6 or not without messing with alphas.

**Comment by pbauer** [comment]
Wrong, since the tests run with 5.2 and 6.0.0a4 and 6.0 coredev all cases need to be covered. I'd rather set `displayed_types` to the defaults of Plone 6  at the beginning of the tests.

**Comment by pbauer** [comment]
I guess now it's ready for merge

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
