### PR TITLE
Remove the disabled flag from @sharing entries

### PR DESCRIPTION
**Pull request by jaroel**
This is a UI flag for Plone templates and does not actually specify that the entry is disabled.

### CODE REVIEW

**Comment by jaroel** [comment]
Maybe some client already depends on this?

**Comment by tisto** [comment]
@jaroel I get that the naming is misleading. Could you elaborate what it actually means? I am wondering why we don't display certain entries in the existing (old-school) sharing view.

**Comment by jaroel** [comment]
@tisto We do display the entries in the existing UI, but the inputs are disabled.
See https://github.com/plone/plone.app.workflow/blob/master/plone/app/workflow/browser/sharing.py#L266

**Comment by tisto** [comment]
@jaroel thanks for the clarification. Though, don't we need this information to render the users/roles table in JS then? One could argue that we should fix the naming. Though, I think we still need this kind of information in the front-end.

**Comment by tisto** [comment]
@jaroel reminder: please reply to my last comment. :)

**Comment by jaroel** [comment]
@tisto right, in plone-react we do disable the UI, but the logic for that is in the UI.
I've removed this field from the response so we only deal with actual state.
I can add it again, though

**Comment by jaroel** [comment]
Lets leave it in; might be easy for UI purposes.

**Pull request closed without merging**
