### PR TITLE
5.1b4

### PR DESCRIPTION
**Pull request by tisto**
Do not run test_documentation for Plone > 5.0. This is a workaround for https://github.com/plone/plone.restapi/issues/470

### CODE REVIEW

**Comment by tisto** [comment]
@lukasgraf it seems freezegun does not work well with the latest ZODB related upgrades we did for Plone 5.1b4: 

https://github.com/plone/buildout.coredev/commit/b58ef87a14d20fb400e33e86c61c96a6fac97aab

(I wasn't really able to prove this yet though)

Not running test_documentation for Plone > 5.0 is just a workaround.

**Comment by lukasgraf** [comment]
@tisto I only had time to take a cursory glance at this, but it wasn't obvious to me from the couple travis failures I looked at why `freezegun` would be responsible for them. Any way I can help?

If `freezegun` turns out to be a blocker, we could always incorporate [our approach from `ftw.testing` (freezer)](https://github.com/4teamwork/ftw.testing#freezing-datetime-now). That uses [`forbiddenfruit`](https://github.com/clarete/forbiddenfruit) though, which we require to patch builtin classes written in C - never had any issues with it, but I wouldn't feel comfortable including `forbiddenfruit` as anything other than a test-only dependency.

**Comment by lukasgraf** [comment]
@tisto FYI: I just did a test on current `master` locally with removing the

```
        if PLONE_VERSION.base_version >= '5.1':
            self.skipTest('Do not run documentation tests for Plone 5')
```

skips from `test_documentation.py` - tests passed for me on Plone 5.x without a problem. I think the `freezegun` stuff might have been a fluke, and we can unskip those "tests".

**Comment by tisto** [comment]
@lukasgraf create a pr and let give it a try.

**Pull request merged**
