### PR TITLE
Multilingual endpoint to contain information about the current INavigationRoot

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@sneridagh seems like plone.app.caching tests are returning a 500 error on coredev tests...

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
