### PR TITLE
Add subblocks transformer support

### PR DESCRIPTION
**Pull request by tiberiuichim**
Fixes https://github.com/plone/plone.restapi/issues/1084

### CODE REVIEW

**Review by cekk — APPROVED** [review]

**Comment by cekk** [comment]
LGTM
Just to know: is this will be the standard of managing subblocks? Because we are using them in a different way (\cc @nzambello @giuliaghisini)

**Comment by tiberiuichim** [comment]
@cekk I'm aware that volto-subblocks uses another storage scheme, but I wasn't 100% sure how that looks like, and I made a deal with Nicola that I'll push this implementation and you can complement how the subblocks are found. My proposal is that you push changes to this PR with our storage specifics, should be easy enough. You'll have to add your implementation here: https://github.com/plone/plone.restapi/pull/1085/files#diff-6ad4a25ea7136e36c0d249c9361fff5494a7bf28825b8e7702cc35f189bcef43R79

**Comment by tiberiuichim** [comment]
@cekk I've also checked with @sneridagh and they don't have subblocks, so there's just these 2 cases to be handled.

**Comment by tiberiuichim** [comment]
@cekk: See also related issue, where I'm detailing how to write a transformer-based subblocks implementation: https://github.com/plone/plone.restapi/issues/1084

**Comment by tiberiuichim** [comment]
@jenkins-plone-org please run jobs

**Comment by tiberiuichim** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@cekk @tiberiuichim we should talk about our grid/sub-blocks implementations and try to unify our approaches. As far as I know @tiberiuichim and @sneridagh already kind of did this.

**Comment by cekk** [comment]
I like @tiberiuichim implementation and that we should unify our approaches (i ping @nzambello  and @giuliaghisini for that).

I already made a super generic transformer [here](https://github.com/RedTurtle/redturtle.volto/blob/master/src/redturtle/volto/restapi/serializer/blocks.py#L21) because we have a different pattern: we store subblocks that are not real blocks but only a list of "a bunch of data with the same shape".

So: for me it's a big 👍  this approach basically because we can also use proper transformers and not a recursion hell like in our implementation

**Review by sneridagh — APPROVED** [review]

**Review by tisto — APPROVED** [review]

**Pull request merged**
