### PR TITLE
Fix pinns

### PR DESCRIPTION
**Pull request by wesleybl**
- Use specific version of Plone in requirements.txt. As we are using specific version in versions.cfg, we need to use
specific versions in requirements.txt as well, to avoid problems in the future. Ref: #1512

- Remove unnecessary pins.

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
@wesleybl thanks, good catch

**Comment by wesleybl** [comment]
> @wesleybl can you add a changelog in news/1516.internal?

@davisagli Is this really necessary? I don't see that this information would be useful for using plone.restapi. Wouldn't that just be a "change polluter"?

**Comment by davisagli** [comment]
@wesleybl That's why it goes in the internal section, to keep it separate. I see your point, but currently there is a check for a changelog entry on each PR.

**Comment by wesleybl** [comment]
@davisagli done.

**Comment by tisto** [comment]
Hey @wesleybl, thanks a lot for taking care of this! And sorry for my previous comment. I highly value your contributions and it was certainly not your fault that we mixed up things in the repo. Turned out we all had different ideas of what we consider to be best practices. We will try to figure this out together and come up with a clear recommendation for how to handle things.

**Pull request merged**
