### PR TITLE
PasswordResetTool is optional

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
There seems to be an issue with travis-CI.

**Comment by tisto** [comment]
Restarted Travis: https://travis-ci.org/plone/plone.restapi/jobs/291436360

**Comment by tisto** [comment]
@tomgross if we make P.Pwresettool a soft-dependency, integrators will run into issues at run time (because the feature does not work) instead of at build time. Not sure if a hard-dependency isn't the better choice here. 

@sneridagh @csenger @jaroel @buchi @lukasgraf: opinions?

**Comment by erral** [comment]
FWIW on #293 we had to add this dependency because it wasn't included on Plone 5.1, has the situation changed?

**Comment by jaroel** [comment]
This is just fine. Products.PasswordResetTool is a dependency for Products.CMFPlone < 5.1, so no runtime errors for integrators.

See https://github.com/plone/Products.CMFPlone/commit/fbbc911e9e8566e33d7bc17ef1a0b4bb6e6a4aad#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by tomgross** [comment]
The only place Products.PasswordResetTool is used is here: https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/users/add.py#L25
And this works for all supported Plone versions.

 * 4.3 (PasswordResetTool is a hard dependency of CMFPlone itself)
 * 5.0 (PasswordResetTool is a hard dependency of CMFPlone itself)
 * 5.1 (PasswordResetTool moved to CMFPlone and needed componets are imported from there)

Integrators will not run into any troubles with this change.

**Pull request merged**
