### PR TITLE
Add a converter for Decimal() objects.

### LINKED ISSUE #963: Missing converter for Decimal()
I have a content type containing a Decimal field defined as:

```
    hike_distance = schema.Decimal(
        title=_(u'Distance'),
        description=u'''
        ''',
        min=Decimal(0),
        required=False,
    )
```

When I try to request objects of this content type directly or with `fullobjects` or with `metadata_fields=hike_distance`, I get an error `TypeError: No converter for making Decimal('12') (<class 'decimal.Decimal'>) JSON compatible.`

Indeed, as the error says, there is no converter for Decimal even though it is [documented](https://plonerestapi.readthedocs.io/en/latest/types-schema.html#decimal).  Moreover, the serializer test for Decimal seems to be incorrect, as it merely serializes a string instead of a Decimal object.

### PR DESCRIPTION
**Pull request by fulv**
Fixes #963

### CODE REVIEW

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
I don't know why travis ran the tests on master.

@jenkins-plone-org please run jobs

**Comment by fulv** [comment]
@tisto I am in sync with master and I don't see anything in master that would fix #963

**Comment by tisto** [comment]
@fulv I fixed this issue in master:

```
$ bin/code-analysis
Flake8..........................[ FAILURE ] in 8.952s
/home/travis/build/plone/plone.restapi/src/plone/restapi/tests/test_serializer.py:395:5: F811 redefinition of unused 'test_serialize_to_json_collection_include_items' from line 361
```

As said, rebase and this error is gone.

**Comment by tisto** [comment]
@fulv just to be clear. I am talking about the Travis failures.

**Pull request closed without merging**
