### PR TITLE
Test Python 3.12 on GHA

### PR DESCRIPTION
**Pull request by tisto**
@gforcada are you already working on Python 3.12 for plone.restapi or did I get your comment about this on community.plone.org wrong?

https://community.plone.org/t/experiment-plone-6-0-7-on-python-3-12-0/17993/4

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
We can't officially declare support for Python 3.12 until there are releases of RestrictedPython and Zope that officially support it, right?

**Comment by tisto** [comment]
@davisagli fair point. I wasn't aware of this...

**Comment by gforcada** [comment]
The coordination issue for 3.12 is: https://github.com/plone/Products.CMFPlone/issues/3852

So far the tests for plone.api and plone.restapi are fixed, a few new version pins are needed (added by @pbauer ) and the jenkins jobs need to be hooked up so we do not regress, but the jobs are there.

**Review by mauritsvanrees — APPROVED** [review]
LGTM.  I have merged the `plone.rest` PR just now.

> We can't officially declare support for Python 3.12 until there are releases of RestrictedPython and Zope that officially support it, right?

True for Plone as a whole, but for me it is fine if `plone.restapi` already declares 3.12 support.

For me it is fine to merge as-is.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
