### PR TITLE
Serialize lock information on dx content

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by tisto** [comment]
@avoinea is this PR ready for review? Could you add a changelog entry?

**Comment by avoinea** [comment]
Yes. Changelog not needed as it is already within the base branch.

**Comment by tiberiuichim** [comment]
What about "can_unlock" instead of "stealable" ?

**Comment by tisto** [comment]
@avoinea I don't get it. Don't you want me to merge this PR first and then the older one? Then we need a changelog entry.

**Comment by tiberiuichim** [comment]
@tisto I think @avoinea is looking for feedback on these particular set of changes, as a separate part of the main lock PR. He can do the merge into the main Lock PR once he's satisfied, I guess.

**Comment by tisto** [comment]
@tiberiuichim @avoinea the code in this PR looks good to me. If we have a changelog entry I can merge it right away. I am also ok with having one big PR with everything.

**Comment by tiberiuichim** [comment]
@tisto @avoinea is now in vacation, that's why I was answering for him. I think we should wait until he returns?

**Pull request merged**
