### PR TITLE
Plone 6.0.7

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
@tisto LGTM assuming tests pass, but you need a towncrier entry

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
We have a problem on GHA:

````
While:
  Installing.
  Getting section sphinxbuilder.
  Initializing section sphinxbuilder.
  Loading zc.buildout recipe entry collective.recipe.sphinxbuilder:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 740, in install
    [self[part]['recipe'] for part in install_parts]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 740, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1373, in __getitem__
    options._initialize()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1481, in _initialize
    self.initialize()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1487, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1441, in _install_and_load
    return pkg_resources.load_entry_point(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 536, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2931, in load_entry_point
    return ep.load()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2517, in load
    self.require(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2540, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.16 (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages), Requirement.parse('docutils<0.21,>=0.18.1'), {'Sphinx'})
````

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@mauritsvanrees I am clueless why we still have this test failure with Plone 5.2.14, plone.namedfile 5.6.1 and plone.rest 3.0.1:

````
Failure in test test_get_own_user_portrait_with_svg (plone.restapi.tests.test_services_users.TestUsersEndpoint)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/case.py", line [59](https://github.com/plone/plone.restapi/actions/runs/6263855208/job/17009192135?pr=1706#step:10:60), in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/runner/work/plone.restapi/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 1110, in test_get_own_user_portrait_with_svg
    self.assertEqual(response.headers["Content-Type"], "image/svg+xml")
  File "/opt/hostedtoolcache/Python/3.7.17/x[64](https://github.com/plone/plone.restapi/actions/runs/6263855208/job/17009192135?pr=1706#step:10:65)/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/case.py", line [69](https://github.com/plone/plone.restapi/actions/runs/6263855208/job/17009192135?pr=1706#step:10:70)3, in fail
    raise self.failureException(msg)
AssertionError: 'text/html; charset=utf-8' != 'image/svg+xml'
- text/html; charset=utf-8
+ image/svg+xml
````

**Comment by davisagli** [comment]
@tisto We don't, I fixed it here: https://github.com/plone/plone.restapi/pull/1706/commits/8affcee2c04806f966782428eaadcb82a555b1aa

**Pull request merged**
