### PR TITLE
Use download link for file links in blocks

### PR DESCRIPTION
**Pull request by csenger**
https://github.com/plone/plone.restapi/issues/930

### CODE REVIEW

**Comment by tisto** [comment]
@csenger I guess this PR will conflict with https://github.com/plone/plone.restapi/pull/915. Would it be possible for you to refactor your PR when I merge the other one first?

**Comment by tisto** [comment]
@csenger can you please solve the merge conflicts? It just occurred to me that we have to merge this one first because it will go into the 6.x.x branch.

**Comment by tisto** [comment]
Note: this PR is based on resolve UID.

**Comment by tisto** [comment]
@csenger can you please resolve the merge conflicts?

**Comment by tisto** [comment]
@csenger I merged @tiberiuichim's block serializer PR. Go ahead and rebase...

**Comment by tisto** [comment]
@csenger Travis fails with code-analysis violations...

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@csenger I think I merged all the other PRs. Can you please look into this and let me know if I can review and/or merge this PR now?

Maybe @iFlameing could write a Cypress acceptance test for this. If you could briefly describe how the test should look like he could take over...

**Comment by csenger** [comment]
> @csenger I think I merged all the other PRs. Can you please look into this and let me know if I can review and/or merge this PR now?

@tisto  This can be reviewed and merged. I updated the PR already to use the new transformers.The only thing that I thought about is if we need to respect the "use resolveuids" setting in the plone control panel. But that is not really subject to this PR. And I'm not sure it is necessary as we do not ship /resolveuid/ urls like the old implementation did IIRC.

> Maybe @iFlameing could write a Cypress acceptance test for this. If you could briefly describe how the test should look like he could take over...

@iFlameing The behavior to test is the following:

* The user creates a file object "testfile".
* The user creates a page "testpage" where he uses a link to "testfile" in the main text (blocks).
* When he views the page it contains a link to the file view http://<portal-url>/testfile where he can view/edit/download the file
* When the user is not logged in he will see an URL to the download of the file http://<portal-url>/testfile/@download/file
* When the user is logged in but does not have edit permissions for the file he will also see an URL to the download of the file http://<portal-url>/testfile/@download/file

**Pull request merged**
