### PR TITLE
Run docs check against Python 3.12

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by davisagli** [comment]
@tisto I added the changelog for you and updated a couple more lines that still said 3.9

**Review by davisagli — APPROVED** [review]
Approved, assuming CI passes

**Comment by tisto** [comment]
@davisagli thank you David!

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
No need to run this on Jenkins, right?  The changed files are not used there.

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
